#!/usr/bin/env bash
# build.sh -- assemble the ColecoVision Fujitzee client with zmac.
#
# Usage: ./build.sh
#
# Output: build/fujitzee.bin, always exactly 32768 bytes -- the assembled
# code based at console $8000, padded, the mailbox pages left clear, and the
# "FUJI" claim signature stamped at image offset 0x7CFC so the mailbox stays
# alive when this image boots. The layout contract is enforced by the
# bring-up's tools/checkrom.py; tools/checksize.py then prints the per-module
# budget table.
#
# Environment:
#   ENDPOINT=...   game server (default https://fujitzee.carr-designs.com/)
#   ZMAC=path      assembler override
#   FUJI_PICO=path cartridge bring-up tree, for checkrom.py and as the last
#                  place to look for zmac
#                  (default ~/Workspace/fujinet-firmware/pico)

set -euo pipefail
cd "$(dirname "$0")"

WINDOW=32768
ORG=0x8000            # the cartridge window's console address
ROM_TOP=0x7800        # image offset: client bytes must stay below this
CLAIM_OFF=$((0x7CFC))

FUJI_PICO=${FUJI_PICO:-$HOME/Workspace/fujinet-firmware/pico}
COLECO_TOOLS="$FUJI_PICO/coleco/tools"

# zmac: an explicit override, then PATH, then a standalone build, then the
# astrocade bring-up's vendored copy, built on demand (see its PROVENANCE.md).
find_zmac() {
    if [ -n "${ZMAC:-}" ]; then echo "$ZMAC"; return; fi
    if command -v zmac >/dev/null 2>&1; then echo zmac; return; fi
    if [ -x "$HOME/Workspace/zmac-1.3/zmac" ]; then
        echo "$HOME/Workspace/zmac-1.3/zmac"; return
    fi
    local tree="$FUJI_PICO/astrocade/tools/zmac"
    if [ -d "$tree" ]; then
        if [ ! -x "$tree/zmac" ]; then
            touch "$tree/zmac.c"    # keep it newer than zmac.y: no yacc wanted
            make -C "$tree" zmac >/dev/null
        fi
        echo "$tree/zmac"; return
    fi
    echo "build.sh: no zmac found; put one on PATH or set ZMAC=" >&2
    exit 1
}

ZMAC=$(find_zmac)
mkdir -p build

# The server the game talks to, overridable without editing source:
#   ENDPOINT=http://127.0.0.1:8080/ ./build.sh
# Regenerated every run so a stale value cannot survive an environment change.
ENDPOINT="${ENDPOINT:-https://fujitzee.carr-designs.com/}"
{
    echo "; generated by build.sh -- do not edit"
    printf 'UENDPT: DB      "%s"\n' "$ENDPOINT"
    echo "        DB      0"
} > build/endpoint.inc

# zmac 1.3 resolves INCLUDE against the cwd; assemble from here.
"$ZMAC" -o build/fujitzee.raw -x build/fujitzee.lst fujitzee.asm

# zmac trims the raw to the lowest address actually emitted, so this file
# starts at ORG -- PROVIDED nothing assembled below it. Anything outside the
# window silently shifts the whole image down and every mailbox address in it
# with it, which is why the header magic is checked rather than assumed. (It
# has happened once already: build/endpoint.inc was included before the ORG,
# and 34 bytes of URL landed at address 0.)
if [ "$(head -c 2 build/fujitzee.raw | xxd -p)" != "55aa" ]; then
    echo "build.sh: image does not start with the cartridge header;" >&2
    echo "  something assembled below $ORG -- check for data outside the ORG" >&2
    exit 1
fi

size=$(wc -c < build/fujitzee.raw)
if [ "$size" -gt "$((ROM_TOP))" ]; then
    echo "build.sh: client is $size bytes, over the $ROM_TOP ROM top" >&2
    exit 1
fi

# Pad to the full window with 0xFF -- the byte an unmapped cartridge address
# reads as, and what checkrom.py accepts as filler -- then stamp the claim.
{
    cat build/fujitzee.raw
    head -c $((WINDOW - size)) /dev/zero | tr '\0' '\377'
} > build/fujitzee.bin
printf 'FUJI' | dd of=build/fujitzee.bin bs=1 seek=$CLAIM_OFF \
    conv=notrunc status=none
rm -f build/fujitzee.raw

python3 "$COLECO_TOOLS/checkrom.py" build/fujitzee.bin
python3 tools/checksize.py build/fujitzee.lst
