#!/usr/bin/env bash
# build.sh -- assemble Fujitzee for the Fairchild Channel F.
#
# Macro Assembler AS with CPU F3850, the same assembler the Arcadia (2650) and
# Odyssey2 (8048) ports use. The image must be EXACTLY 16K with the "FUJI"
# claim at $47FC, or the cartridge boots it with the mailbox dead and the 30K
# arena at $8000 reverts to open bus. tools/checkrom.py --claim enforces it.
#
# Env:
#   ENDPOINT=...   game server (default https://fujitzee.carr-designs.com/)
#   ASL= P2BIN=    assembler overrides (default ~/asl)
set -euo pipefail
cd "$(dirname "$0")"

ASL="${ASL:-$HOME/asl/asl}"
P2BIN="${P2BIN:-$HOME/asl/p2bin}"

[ -x "$ASL" ]   || { echo "build.sh: no assembler at $ASL" >&2; exit 1; }
[ -x "$P2BIN" ] || { echo "build.sh: no p2bin at $P2BIN" >&2; exit 1; }

mkdir -p build

# Regenerated on EVERY run so a stale value cannot survive an environment
# change. 5 Card Stud's Channel F port gitignores endpoint.inc and generates
# it from nothing, so a fresh clone there does not assemble; this does not
# repeat that.
{
    echo "; GENERATED by build.sh -- do not edit"
    printf 'UENDPT:\tDB "%s",0\n' "${ENDPOINT:-https://fujitzee.carr-designs.com/}"
} > src/endpoint.inc

python3 tools/mkfont.py src/font.inc

( cd src && "$ASL" fujitzee.asm -L -i . -q )
# -l 0xff fills the gaps, matching what MAME's stock Videocart answers past its
# ROM. p2bin's -f FILTERS records out (silently empty image) and -s appends a
# checksum byte; neither is wanted.
"$P2BIN" src/fujitzee.p build/fujitzee.bin -r 0x800-0x47ff -l 0xff -q
mv -f src/fujitzee.lst build/fujitzee.lst 2>/dev/null || true
rm -f src/fujitzee.p
python3 tools/checkrom.py build/fujitzee.bin --claim
python3 tools/checksize.py build/fujitzee.lst
echo "build/fujitzee.bin ok"
