#!/usr/bin/env bash
# build.sh -- assemble the Astrocade Fujitzee client with zmac.
#
# Usage: ./build.sh
#
# Output: build/fujitzee.bin, always exactly 8192 bytes: the assembled
# code, zero-padded, mailbox pages clear, "FUJI" claim signature at 0x1CFC
# so the mailbox stays alive when the image is booted over the network. The
# layout contract is enforced by tools/checkrom.py; tools/checksize.py then
# prints the per-module budget table.
#
# Environment:
#   ENDPOINT=...        game server (default https://fujitzee.carr-designs.com/)
#   DEMO=1              assemble the static mock play screen instead of
#                       the game (M1 layout tuning)
#   ZMAC=path           assembler override
#   FUJI_PICO=path      cartridge bring-up tree, only used as the last place
#                       to look for zmac (default
#                       ~/Workspace/fujinet-firmware/pico/astrocade)
#
# Self-contained by design, the way the battleship port is: the layout
# checker is vendored in tools/ and fujilib.inc / HVGLIB.H live here, so a
# build needs no particular branch of the firmware tree checked out. Those
# two are copies of the bring-up's testrom/ files -- keep them in step.

set -euo pipefail
cd "$(dirname "$0")"

WINDOW=8192
CLAIM_OFF=$((0x1CFC))
ROM_TOP=$((0x1B00))

FUJI_PICO=${FUJI_PICO:-$HOME/Workspace/fujinet-firmware/pico/astrocade}

# zmac: an explicit override, then PATH, then a standalone build, then the
# bring-up's vendored copy (built on demand -- see its PROVENANCE.md).
find_zmac() {
    if [ -n "${ZMAC:-}" ]; then
        echo "$ZMAC"
        return
    fi
    if command -v zmac >/dev/null 2>&1; then
        echo zmac
        return
    fi
    if [ -x "$HOME/Workspace/zmac-1.3/zmac" ]; then
        echo "$HOME/Workspace/zmac-1.3/zmac"
        return
    fi
    local tree="$FUJI_PICO/tools/zmac"
    if [ -d "$tree" ]; then
        if [ ! -x "$tree/zmac" ]; then
            touch "$tree/zmac.c"    # keep it newer than zmac.y: no yacc wanted
            make -C "$tree" zmac >/dev/null
        fi
        echo "$tree/zmac"
        return
    fi
    echo "build.sh: no zmac found; put one on PATH or set ZMAC=" >&2
    exit 1
}

ZMAC=$(find_zmac)
mkdir -p build

# The server the game talks to, overridable without editing source:
#   ENDPOINT=http://127.0.0.1:8080/ ./build.sh
# Regenerated every run so a stale value cannot survive an environment change.
ENDPOINT="${ENDPOINT:-https://fujitzee.carr-designs.com/}"
{
    echo "; generated by build.sh -- do not edit"
    printf 'UENDPT: DB      "%s"\n' "$ENDPOINT"
    echo "        DB      0"
} > build/endpoint.inc

# Build flags. DEMO=1 assembles the static mock play screen instead of
# the game.
{
    echo "; generated by build.sh -- do not edit"
    echo "DEMO    EQU     ${DEMO:-0}"
} > build/flags.inc

# zmac 1.3 resolves INCLUDE against the cwd; assemble from here.
"$ZMAC" -o build/fujitzee.raw -x build/fujitzee.lst fujitzee.asm

size=$(wc -c < build/fujitzee.raw)
if [ "$size" -gt "$ROM_TOP" ]; then
    echo "build.sh: fujitzee is $size bytes, over the $ROM_TOP ROM top" >&2
    exit 1
fi

# Pad to the full window, clear above ROM_TOP, stamp the claim.
{
    cat build/fujitzee.raw
    head -c $((WINDOW - size)) /dev/zero
} > build/fujitzee.bin
printf 'FUJI' | dd of=build/fujitzee.bin bs=1 seek=$CLAIM_OFF \
    conv=notrunc status=none
rm -f build/fujitzee.raw

python3 tools/checkrom.py build/fujitzee.bin
python3 tools/checksize.py build/fujitzee.lst
