#!/usr/bin/env python3
"""
Convert the MSDOS port's 8x8 CGA-2bpp font (src/msdos/charset.c) into a
CoCo 3 2bpp tile array. The CoCo 3 screen is 4bpp; hires_putc expands
each 2bpp pixel via text_palette[4] at render time, so this header keeps
the source 2bpp form unchanged (16 bytes/char) and lets us recolor text
by changing the palette.

Input:  src/msdos/charset.c  -- C array  unsigned char charset[256][16]
Output: src/coco/charset_coco3.h
"""
import re, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC  = os.path.join(ROOT, "src", "msdos", "charset.c")
DST  = os.path.join(ROOT, "src", "coco", "charset_coco3.h")

# Highest codepoint emitted (exclusive bound is N_GLYPHS).
N_GLYPHS = 128

with open(SRC, "r") as f:
    text = f.read()

entries = re.findall(r'\{([^}]+)\}', text)
glyphs  = []
for e in entries[:N_GLYPHS]:
    bs = [int(b, 16) for b in re.findall(r'0x[0-9A-Fa-f]+', e)]
    bs = (bs + [0]*16)[:16]
    glyphs.append(bs)

while len(glyphs) < N_GLYPHS:
    glyphs.append([0]*16)

with open(DST, "w") as f:
    f.write("/* Generated by support/coco/cvt_msdos_font.py - do not edit. */\n")
    f.write("/* {N} glyphs x 8 rows x 2 bytes/row, CGA 2bpp.\n".format(N=N_GLYPHS))
    f.write(" * hires_putc expands each 2bpp pixel via text_palette[] at\n")
    f.write(" * render time. */\n\n")
    f.write("#ifndef CHARSET_COCO3_H\n#define CHARSET_COCO3_H\n\n")
    f.write(f"#define CHARSET_COCO3_N {N_GLYPHS}\n\n")
    f.write(f"static const unsigned char charset_coco3[{N_GLYPHS}][16] = {{\n")
    for idx, g in enumerate(glyphs):
        hex_bytes = ", ".join(f"0x{b:02X}" for b in g)
        f.write(f"    /* 0x{idx:02X} */ {{ {hex_bytes} }},\n")
    f.write("};\n\n")
    f.write("#endif\n")

print(f"wrote {DST} ({len(glyphs)} glyphs, {len(glyphs)*16} bytes)")
