#!/usr/bin/env bash
# build.sh -- assemble the Arcadia 2001 Fujitzee client.
#
# Output: build/fujitzee.bin, always exactly 8192 bytes: image
# 0x0000-0x0FFF is CPU $0000-$0FFF (block 1), image 0x1000-0x1FFF is CPU
# $2000-$2FFF (block 2). The assembler works in CPU addresses; p2bin
# emits a $0000-$2FFF flat and the firmware tree's mkimage.py folds it,
# rejecting code in the $1000-$1FFF console-RAM hole or the $2B00+
# mailbox pages. The "FUJI" claim is stamped at image 0x1CFC (without it
# the mailbox goes dead the moment the image boots) and checkrom.py
# enforces the final layout. checkdepth.py bounds the call graph to the
# 2650's 8-entry return stack; checksize.py reports per-module budgets.
#
# Env:
#   ENDPOINT=...      server (default https://fujitzee.carr-designs.com/)
#   FUJI_FIRMWARE=... firmware tree (default ~/Workspace/fujinet-firmware)

set -euo pipefail
cd "$(dirname "$0")"

FUJI_FIRMWARE="${FUJI_FIRMWARE:-$HOME/Workspace/fujinet-firmware}"
ARC="$FUJI_FIRMWARE/pico/arcadia"
CLAIM_OFF=$((0x1CFC))

AS_BIN="${AS_BIN:-$HOME/Workspace/o2workspace/bin}"
if command -v asl >/dev/null 2>&1; then
    AS=asl P2BIN=p2bin
elif [ -x "$HOME/asl/asl" ]; then
    AS="$HOME/asl/asl" P2BIN="$HOME/asl/p2bin"
else
    AS="wine $AS_BIN/asw.exe" P2BIN="wine $AS_BIN/p2bin.exe"
    export WINEDEBUG=-all
fi

mkdir -p build

# Regenerated every run so a stale value cannot survive an environment
# change (the astrocade port's rule).
{
    echo "; generated by build.sh -- do not edit"
    printf 'UENDPT: DB      "%s"\n' "${ENDPOINT:-https://fujitzee.carr-designs.com/}"
    echo "        DB      0"
} > build/endpoint.inc

$AS -q -L fujitzee.asm -o build/fujitzee.p -olist build/fujitzee.lst
$P2BIN build/fujitzee.p build/fujitzee.flat -r '$0000-$2FFF' -l 0
python3 "$ARC/tools/mkimage.py" build/fujitzee.flat build/fujitzee.bin
printf 'FUJI' | dd of=build/fujitzee.bin bs=1 seek=$CLAIM_OFF conv=notrunc status=none
rm -f build/fujitzee.p build/fujitzee.flat
python3 "$ARC/tools/checkrom.py" build/fujitzee.bin
python3 "$ARC/tools/checkdepth.py" fujitzee.asm ./*.inc assets/udc.inc
[ -f tools/checksize.py ] && python3 tools/checksize.py build/fujitzee.lst
echo "build/fujitzee.bin ok"
