#!/usr/bin/env python3
"""mkdice.py -- generate src/diceart.inc, the five dice the kernel streams.

A die is ONE sprite object: 8 colour clocks wide, DIEH scanlines tall, one
byte a line with bit 7 leftmost. Seven of the eight pixels are body and the
eighth is the gutter between dice, so a face is drawn on a 7x12 grid.

TWO VARIANTS, and the difference is deliberately not a colour. In a 48-pixel
six-copy span COLUP0 paints dice 0, 2 and 4 and COLUP1 dice 1 and 3, so a
per-die colour does not exist on this console. The held state is therefore in
the ART:

    ordinary   a solid body with the pips PUNCHED THROUGH to the blue page,
               which is what a die actually looks like -- white, blue pips
    held       the body gone and only a bar above and below, with the pips
               drawn IN INK between them: a bracket, the same device
               battleship uses for a hull, and it cannot be confused with a
               solid die at any size

The layout the kernel indexes is  FZART + held*DIEVAR + face*DIEH,  face 0-5,
so the highest low byte is 72 + 60 + 11 = 143 -- comfortably inside one page,
which is what keeps `lda (DPTRn),y` at five cycles for every face.
"""

W, H = 7, 12
PIPCOL = {"L": 1, "C": 3, "R": 5}
PIPROW = {"T": 2, "M": 5, "B": 8}        # each pip is 1 wide x 2 tall

# The six faces, as the pip positions they light.
FACES = [
    ["CM"],                                      # 1
    ["LT", "RB"],                                # 2
    ["LT", "CM", "RB"],                          # 3
    ["LT", "RT", "LB", "RB"],                    # 4
    ["LT", "RT", "CM", "LB", "RB"],              # 5
    ["LT", "RT", "LM", "RM", "LB", "RB"],        # 6
]


def grid(face, held):
    """A 12 x 7 grid of booleans: True = ink."""
    if held:
        g = [[False] * W for _ in range(H)]
        for x in range(W):                        # the bracket bars
            g[0][x] = g[H - 1][x] = True
        ink = True                                # pips are drawn IN ink
    else:
        g = [[True] * W for _ in range(H)]        # a solid body
        ink = False                               # pips are punched OUT
    for pip in face:
        cx, ry = PIPCOL[pip[0]], PIPROW[pip[1]]
        for dy in range(2):
            g[ry + dy][cx] = ink
    return g


def rows(face, held):
    out = []
    for line in grid(face, held):
        b = 0
        for x, on in enumerate(line):
            if on:
                b |= 0x80 >> x                    # bit 7 is the leftmost pixel
        out.append(b)
    return out


def main():
    print("; diceart.inc -- GENERATED by tools/mkdice.py. Do not edit.")
    print(";")
    print("; ORG FZART in every bank that draws dice, and the 144 bytes must be")
    print("; byte-identical between them: DPTRn+1 is written once by DINIT and the")
    print("; network bank never runs it. tools/checkart.py enforces that.")
    print()
    print("        ORG     FZART")
    print("DICEART:")
    for held in (0, 1):
        print("; %s" % ("held: a bracket, pips in ink" if held
                        else "ordinary: a solid body, pips punched through"))
        for i, face in enumerate(FACES):
            art = rows(face, held)
            pic = ["".join("#" if c else "." for c in ln)
                   for ln in grid(face, held)]
            print("        DB      %s   ; %d  %s" % (
                ",".join("$%02X" % b for b in art[:6]), i + 1,
                " ".join(pic[:6])))
            print("        DB      %s   ;    %s" % (
                ",".join("$%02X" % b for b in art[6:]),
                " ".join(pic[6:])))
    print()
    print("DICEEND:")
    print("        IF      DICEEND-DICEART <> 2*DIEVAR")
    print("        ERROR   \"diceart.inc: wrong size\"")
    print("        ENDIF")


if __name__ == "__main__":
    main()
