#!/usr/bin/env python3
"""mklayout.py -- the layout ROM's screen, baked into the image.

Writes build/layoutscr.inc: ORG'd DB blocks that put the six text planes at
$1800-$1AFF, so a flat 4K image shows a whole scorecard with no cartridge and
no network at all. The kernel, the per-row colours, the green potentials, the
dice band and the cursor bar are the one part of this port with no template
anywhere, and they all have to be right before any of them is worth debugging
over a socket.

emu/scrcheck.py imports SCREEN from here to read a snapshot back, so the baked
image and the test cannot drift apart.
"""

import sys, os

sys.path.insert(0, os.path.join(
    os.environ.get("FUJI_FIRMWARE", os.path.expanduser("~/Workspace/fujinet-firmware")),
    "pico/atari-2600/tools"))
import vcsfont                                                    # noqa: E402

COLS, ROWS = 12, 21
T_BASE, PLANE_LEN, PLANES = 0x1800, 0x80, 6


def row(label, value=None):
    """A card row: an 8-column label and a 3-column right-aligned value."""
    if value is None:
        return label[:COLS].ljust(COLS)
    return (label[:8].ljust(8) + " " + str(value)[:3].rjust(3))


# The picture. Every state the kernel can paint appears at least once, and no
# two adjacent rows are the same, so a row drawn from the wrong plane offset
# or coloured from the wrong mask bit is visible.
#
# GREEN marks the rows the potential mask lights: open categories with
# something to score. DASH is a closed row -- drawn in the page colour, so it
# reads as absent rather than dim. The cursor sits on SM STRT.
CARD = [
    ("ONE",       "3",   False),
    ("TWO",       "6",   False),
    ("THREE",     "12",  False),
    ("FOUR",      "8",   True),
    ("FIVE",      "20",  False),
    ("SIX",       "18",  True),
    ("UP  59 B 0", None, False),      # the two computed upper rows share one
    ("SET 3",     "24",  True),
    ("SET 4",     "-",   False),      # closed
    ("FULL HSE",  "25",  False),
    ("SM STRT",   "30",  True),       # ...and the cursor is here
    ("LG STRT",   "-",   False),      # closed
    ("CHANCE",    "22",  True),
    ("FUJITZEE",  "50",  False),
    ("TOTAL",     "236", False),
]

DICE = [3, 6, 1, 5, 2]                 # faces 1-6, left to right
HELD = [0, 1, 0, 0, 1]                 # die 1 and die 4 are kept
CURSOR = 2                             # the bar sits under die 2


def screen():
    s = ["R 7/13   T45", ">ALICE      "]
    for label, value, _ in CARD:
        s.append(row(label, value))
    s += ["", ""]                      # rows 17-18: the dice band, not planes
    hold = "".join("==" if h else "  " for h in HELD)
    s.append(hold.ljust(COLS))
    s.append("ROLL      X2")
    assert len(s) == ROWS, len(s)
    for i, line in enumerate(s):
        assert len(line) <= COLS, (i, line)
    return s


def mask():
    """The potential mask: row R's bit is bit 16-R. See disp.inc's seam."""
    m = 0
    for i, (_, _, green) in enumerate(CARD):
        if green:
            m |= 1 << (16 - (2 + i))
    return m


def main():
    blob = vcsfont.pack_screen(screen())
    print("; generated by tools/mklayout.py -- do not edit")
    print("LMASK0  EQU     $%02X" % (mask() >> 8))
    print("LMASK1  EQU     $%02X" % (mask() & 0xFF))
    print("LFACES: DB      " + ",".join(str(d - 1) for d in DICE))
    # FZKEEP carries the WIRE's sense: a set bit means that die RE-ROLLS, so a
    # held die is a CLEAR bit. Getting this backwards is the trap every port
    # in the family writes down.
    keep = sum(0 if h else (1 << i) for i, h in enumerate(HELD))
    print("LKEEP   EQU     $%02X" % keep)
    print("LCURSOR EQU     %d" % CURSOR)
    for p in range(PLANES):
        chunk = blob[p * PLANE_LEN:(p + 1) * PLANE_LEN]
        print("        ORG     $%04X" % (T_BASE + p * PLANE_LEN))
        for i in range(0, PLANE_LEN, 12):
            print("        DB      " +
                  ",".join("$%02X" % b for b in chunk[i:i + 12]))


if __name__ == "__main__":
    main()
