#!/usr/bin/env python3
"""mkudc.py -- generate assets/udc.inc, the UDC bank for the client.

The 2637 UVI has 8 user-defined characters at $1980-$19BF (codes $38-$3F),
8 bytes each, bit 7 leftmost, and THE FIRST FOUR double as the sprite
images. Fujitzee uses exactly one sprite -- the scorecard cursor chevron --
so slot $38 must hold that shape; the rest are ordinary glyphs and there
is only ever one bank, loaded once at boot.

The dice are the interesting part. A die is 2 cells wide by 3 tall
(16x24 px), drawn as a SOLID BODY in the die's state colour with the pips
punched through to the blue page -- so the pips cost nothing but holes,
and the die's colour says whether it is ordinary, held or under the
cursor. Because the pip holes land at the same cell-relative position in
both columns and in all three rows, all six faces are built from just
three glyphs plus the built-in full-cell solid block ($03):

    left column pip   cell x2-5   -> die x2-5     PIP
    right column pip  cell x2-5   -> die x10-13   PIP  (same glyph)
    centre pip        die x6-9    -> PIPCL (cell x6-7) + PIPCR (cell x0-1)

which leaves the die a 2px solid border all round and a 4px gap between
pip rows. The face->cell map is FACETAB in tables.inc.

Every emitted byte carries the row's art in the comment so the generated
file reviews by eye. Output is committed; regenerate with `make assets`.
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "assets" / "udc.inc"

# 8x8 art, '#' = ink.
GLYPHS = {
    # $38 -- sprite 0's image: the scorecard cursor. A solid chevron
    # pointing back at the value field it sits beside. Normal (4-ink) mode
    # has no second background, so there is no inverse cell to mark the
    # cursor with -- this sprite is what makes it unmistakable, and it
    # carries its own colour independent of the four screen inks.
    "CHEVR": [
        "...#....",
        "..##....",
        ".###....",
        "####....",
        "####....",
        ".###....",
        "..##....",
        "...#....",
    ],
    # $39 -- a die cell with one pip punched out of the solid body. Serves
    # both the left column (die x2-5) and the right (die x10-13).
    "PIP": [
        "########",
        "########",
        "##....##",
        "##....##",
        "##....##",
        "##....##",
        "########",
        "########",
    ],
    # $3A -- the LEFT half of the centre pip, at the right edge of the
    # die's left cell (cell x6-7 = die x6-7).
    "PIPCL": [
        "########",
        "########",
        "######..",
        "######..",
        "######..",
        "######..",
        "########",
        "########",
    ],
    # $3B -- the RIGHT half of the centre pip, at the left edge of the
    # die's right cell (cell x0-1 = die x8-9). With PIPCL it forms one
    # 4x4 pip centred on the die at x6-9.
    "PIPCR": [
        "########",
        "########",
        "..######",
        "..######",
        "..######",
        "..######",
        "########",
        "########",
    ],
    "BLANK": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
}

BANK = ["CHEVR", "PIP", "PIPCL", "PIPCR", "BLANK", "BLANK", "BLANK", "BLANK"]


def rowbyte(row: str) -> int:
    assert len(row) == 8, row
    v = 0
    for i, ch in enumerate(row):
        assert ch in "#.", row
        if ch == "#":
            v |= 0x80 >> i
    return v


def main() -> None:
    for name, art in GLYPHS.items():
        assert len(art) == 8, name

    lines = [
        "; udc.inc -- generated by tools/mkudc.py; do not edit.",
        ";",
        "; The 64-byte UDC bank for $1980-$19BF (glyph codes $38-$3F). Slot",
        "; $38 is also sprite 0's image, which is why the cursor chevron",
        "; lives there. Loaded once at boot by UDCLD below (page-1 code: the",
        "; data is in block 2, the UDC RAM is page 0, so the copy runs",
        "; through the PUDC pointer).",
        ";",
        "; $39-$3B are the dice: a solid body with the pips punched out to",
        "; the page. See the module docstring in tools/mkudc.py.",
        "",
        "UDCBK:",
    ]
    total = 0
    for slot, name in enumerate(BANK):
        lines.append(f"; ${0x38 + slot:02X} {name}")
        for row in GLYPHS[name]:
            b = rowbyte(row)
            lines.append(f"        DB      %{b:08b}        ; {row}")
            total += 1
    lines.append("")

    lines.append("""\
; UDCLD: load the bank into the UDC RAM. Page-1 code; clobbers R0,R3.
UDCLD:  LODI,R3 63
UDCL1:  LODA,R0 UDCBK,R3
        STRA,R0 *PUDC,R3
        BDRR,R3 UDCL1
        LODA,R0 UDCBK
        STRA,R0 *PUDC
        RETC,UN

PUDC:   DWBE    UDC
""")

    assert total == 64, total
    OUT.write_text("\n".join(lines))
    print(f"{OUT}: {total} bytes of UDC art")


if __name__ == "__main__":
    main()
